/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LogUtil
{
  public enum MyLogType
  {
    COMMON = 1,
    WARNING = 2,
    ERROR = 4,
    EXCEPTION = 8,
  }
}
